[author]
author_full_name="Andrea Hrelja"
author_email="andhrelja@hotmail.com"
author_github="https://github.com/andhrelja"
author_github_pretty="github/andhrelja"
author_website="https://www.linkedin.com/in/andhrelja/"
author_website_pretty="linkedin/andhrelja"
author_about="IT enthusiast coming from Istra county in Croatia. During my 4 years of professional experience as a Data Engineer, I have worked with various production systems and clients, as a team member and as a one-man band. I am a positive, detail-oriented, productive individual with a can-do attitude, ready to start working on that new project."


[[professional_experience]]
company_name="Kern AI"
company_location="Gerhart-Hauptmann-Allee 71, Eichwalde"
project_name="Cloud Infrastructure"
project_summary="Migrate Digital Ocean deployed production system to Azure Kubernetes Service"
start_dt="11/2023"
end_dt="Present"
project_role="Cloud Engineer"
project_involvement=[
    "Designed a system migration plan (on-prem and Digital Ocean to Azure Kubernetes Service) with the team",
    "Consolidated environment-specific infrastructure stacks into a single OpenTofu stack, orchestrated by GitHub Actions",
]
sdlc_phases="Strategy, Design, Development, Testing, Maintenance"

[[professional_experience]]
company_name="iOLAP"
company_location="Rijeka, Croatia (TX, USA)"
project_name="Banking Industry"
project_summary="Build a CI/CD system to streamline DW development on Snowflake for multiple teams in the organization"
start_dt="12/2021"
end_dt="11/2023"
project_role="DataOps Engineer"
project_involvement=[
    "Developed a version controlled SQL CI/CD solution designed by a System Architect using Python, AWS and Snowflake technologies (CodeBuild, GitHub (Actions), Flyway, custom Python packages)",
    "A colleague DevOps Engineer and I developed the CI/CD from scratch, collaborating with the client and the solution users (multiple SQL development teams) in a \"Startup\" fashion",
    "Directly communicated with the client and was involved in business decisions (discovery, requirements, strategy)"
]
sdlc_phases="Strategy, Design, Development, Testing, Maintenance"

[[professional_experience]]
company_name="iOLAP"
company_location="Rijeka, Croatia (TX, USA)"
project_name="Hospitality Industry"
project_summary="Build a Data Warehouse (ELT + DW)"
start_dt="07/2021"
end_dt="10/2021"
project_role="Data Engineer"
project_involvement=[
    "Developed an ETL solution designed by a System Architect using Python and AWS technologies (DynamoDB, Glue, Lake Formation, Lambda, Redshift, dbt)",
    "Collaborated with the System Architect to design the system and a DevOps Engineer to design the AWS infrastructure",
    "Not included in business decisions or client communication, my focus was delivering a reliable ELT system"
]
sdlc_phases="Design, Development, Testing"

[[professional_experience]]
company_name="iOLAP"
company_location="Rijeka, Croatia (TX, USA)"
project_name="Oil \\& Gas Industry"
project_summary="Support and Enhance an existing infrastructure"
start_dt="03/2020"
end_dt="06/2021"
project_role="BI Developer"
project_involvement=[
    "Collaborated on supporting and enhanceing enterprise ETL solutions using Oracle and other technologies (Oracle ODI, Oracle WebLogic, Tibco Data Virtualization, Spotfire BI)",
    "Working with an enterprise production system and a well-structured Azure Boards, I transitioned into a Mid Data Engineer",
    "Included in analyses that impact business decisions, mostly in the discovery phases where I would elaborate effects of proposed solutions to the client"
]
sdlc_phases="Design, Development, Testing, Maintenance"

[[professional_experience]]
company_name="iOLAP"
company_location="Rijeka, Croatia (TX, USA)"
project_name="Banking Industry"
project_summary="Build a Data Warehouse (DW only)"
start_dt="08/2019"
end_dt="02/2020"
project_role="SQL Developer"
project_involvement=[
    "Collaborated on a DW development using pure SQL on on-prem servers",
    "Created automated Python tests",
    "Not included in business decisions or client communication"
]
sdlc_phases="Development, Testing"


[education]
institution_name="Faculty of Informatics and Digital Technologies, University of Rijeka"
education_outcome="Master's degree, Computer Engineering"
start_dt="10/2020"
end_dt="12/2022"
related_work="Master's thesis: \\href{{https://zir.nsk.hr/islandora/object/infri%3A999}}{{\\texttt{{Information Spread Analysis on Twitter}}}}"


[published_works]
title="Prediction of COVID-19 tweeting: classification based on graph neural networks"
authors="M. Petrović, A. Hrelja, A. Meštrović"
doi="10.23919/MIPRO55190.2022.9803426"


[programming_experience]
languages="Python, SQL (any), Bash, JavaScript, \\LaTeX"
technologies="Oracle, AWS, Snowflake, GitHub Actions, Django, dbt, Flyway..."


[languages]
Croatian="First language (L1) \\\\"
English="C1 \\\\"
Italian="A2 \\\\"
